CASE_ID_COL = "safetyreportid"
SERIOUS_COL = "serious"
ALERT_COL = "fulfillexpeditecriteria"
REACTION_COL = "patient_reaction_reactionmeddrapt"
OUTCOME_COL = "patient_reaction_reactionoutcome"
SEX_COL = "patient_patientsex"
COUNTRY_COL = "occurcountry"
AGE_GROUP_COL = "age_group"
DATE_COL = "receivedate"

DEATH_COL = "seriousnessdeath"
LIFE_THREATENING_COL = "seriousnesslifethreatening"
HOSPITALIZATION_COL = "seriousnesshospitalization"
DISABLING_COL = "seriousnessdisabling"
CONGENITAL_ANOMALY_COL = "seriousnesscongenitalanomali"
OTHER_SERIOUS_COL = "seriousnessother"
REPORTER_QUALIFICATION_COL = "primarysource_qualification"